apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-playground-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: dataieb.com
    http:
      paths:
      - path: /kafka-src-app(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: kafka-playground-service
            port:
              number: 80
