apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-lab-app
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-lab-app
  template:
    metadata:
      labels:
        app: data-lab-app
    spec:
      tolerations:
      - key: "lab"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      nodeSelector:
        role: "lab"
      containers:
      - name: app
        image: 248189947068.dkr.ecr.sa-east-1.amazonaws.com/flask:latest
        ports:
        - containerPort: 80
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-brokers:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: data-lab-service
  namespace: lab
spec:
  selector:
    app: data-lab-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
